name: dart_dependencies_manager
description: A simple dependencies manager
version: 1.0.2
publish_to: none

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  # Dependency Injection
  get_it: ^7.1.4

dev_dependencies:
  # Linting and Code analysis
  dart_lint_rules:
    git:
      url: git@github.com:fabriziocacicia/dart_lint_rules.git
      ref: v0.0.2
